routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('dashboard');

Route::resource('users', 'UserController');
Route::resource('products', 'ProductController');
Route::get('/operations/list/{filter}', 'OperationController@index')->name('operations.list');
Route::get('/operations/search', 'OperationController@search')->name('operations.search');
Route::get('/operations', function () {
    return redirect()->route('dashboard');
});
Route::resource('operations', 'OperationController', ['except' => ['index']]);

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'code', 'price_in', 'price_out', 'unit', 'presentation',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    public function currentTotal()
    {
        return 0;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('products/productList', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products/productCreate');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = Product::create([
            'code'          => $request->input('code'),
            'name'          => $request->input('name'),
            'price_in'      => $request->input('price_in'),
            'price_out'     => $request->input('price_out'),
            'unit'          => $request->input('unit'),
            'presentation'  => $request->input('presentation'),
        ]);
        return redirect()->route('products.show', ['product' => $product]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products/productDetail', ['product' => $product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products/productEdit', ['product' => $product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $product->code          = $request->input('code');
        $product->name          = $request->input('name');
        $product->price_in      = $request->input('price_in');
        $product->price_out     = $request->input('price_out');
        $product->unit          = $request->input('unit');
        $product->presentation  = $request->input('presentation');
        $product->save();
        return redirect()->route('products.show', ['product' => $product]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('products.index');
    }
}

resources/views/products/productCreate.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-primary">
                <div class="panel-heading">Crear Producto</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('products.store') }}">
                    <fieldset>
                        {{ csrf_field() }}
                        {{ method_field('POST') }}

                        <div class="form-group{{ $errors->has('code') ? ' has-error' : '' }}">
                            <label for="code" class="col-md-4 control-label">Código</label>

                            <div class="col-md-6">
                                <input id="code" type="text" class="form-control" name="code" required autofocus>

                                @if ($errors->has('code'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('price_in') ? ' has-error' : '' }}">
                            <label for="price_in" class="col-md-4 control-label">Precio de entrada</label>

                            <div class="col-md-6">
                                <input id="price_in" type="text" class="form-control" name="price_in" required autofocus placeholder="$000.00">

                                @if ($errors->has('price_in'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('price_in') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('price_out') ? ' has-error' : '' }}">
                            <label for="price_out" class="col-md-4 control-label">Precio de salida</label>

                            <div class="col-md-6">
                                <input id="price_out" type="text" class="form-control" name="price_out" required autofocus placeholder="$000.00">

                                @if ($errors->has('price_out'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('price_out') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('unit') ? ' has-error' : '' }}">
                            <label for="unit" class="col-md-4 control-label">Unidades</label>

                            <div class="col-md-6">
                                <input id="unit" type="text" class="form-control" name="unit" required>

                                @if ($errors->has('unit'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('unit') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('presentation') ? ' has-error' : '' }}">
                            <label for="presentation" class="col-md-4 control-label">Presentación</label>

                            <div class="col-md-6">
                                <input id="presentation" type="text" class="form-control" name="presentation" required>

                                @if ($errors->has('presentation'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('presentation') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-raised btn-success">
                                    Crear producto
                                </button>
                                <a href="{{ url()->previous() }}" class="btn btn-raised btn-danger">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/productDetail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-primary">
                <div class="panel-heading">Ver Datos de Producto {{ $product->code }}</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="">
                    <fieldset>
                        {{ csrf_field() }}
                        {{ method_field('POST') }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="code" class="col-md-4 control-label">Código</label>

                            <div class="col-md-6">
                                <input disabled id="code" type="text" class="form-control" name="code" value="{{ $product->code }}" required autofocus>

                                @if ($errors->has('code'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre</label>

                            <div class="col-md-6">
                                <input disabled id="name" type="text" class="form-control" name="name" value="{{ $product->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('price_in') ? ' has-error' : '' }}">
                            <label for="price_in" class="col-md-4 control-label">Precio de entrada</label>

                            <div class="col-md-6">
                                <input disabled id="price_in" type="text" class="form-control" name="price_in" value="{{ $product->price_in }}" required autofocus placeholder="$000.00">

                                @if ($errors->has('price_in'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('price_in') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('price_out') ? ' has-error' : '' }}">
                            <label for="price_out" class="col-md-4 control-label">Precio de salida</label>

                            <div class="col-md-6">
                                <input disabled id="price_out" type="text" class="form-control" name="price_out" value="{{ $product->price_out }}" required autofocus placeholder="$000.00">

                                @if ($errors->has('price_out'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('price_out') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('unit') ? ' has-error' : '' }}">
                            <label for="unit" class="col-md-4 control-label">Unidades</label>

                            <div class="col-md-6">
                                <input disabled id="unit" type="text" class="form-control" name="unit" value="{{ $product->unit }}" required>

                                @if ($errors->has('unit'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('unit') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('presentation') ? ' has-error' : '' }}">
                            <label for="presentation" class="col-md-4 control-label">Presentación</label>

                            <div class="col-md-6">
                                <input disabled id="presentation" type="text" class="form-control" name="presentation" value="{{ $product->presentation }}" required>

                                @if ($errors->has('presentation'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('presentation') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <a href="{{ route('products.edit',$product->id) }}" class="btn btn-raised btn-primary">
                                    Editar producto
                                </a>
                                <a href="{{ route('products.index') }}" class="btn btn-raised btn-danger">
                                    ir al listado
                                </a>
                            </div>
                        </div>
                    </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/productEdit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-primary">
                <div class="panel-heading">Editar Datos de Producto {{ $product->code }}</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('products.update',$product->id) }}">
                    <fieldset>
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="code" class="col-md-4 control-label">Código</label>

                            <div class="col-md-6">
                                <input id="code" type="text" class="form-control" name="code" value="{{ $product->code }}" required autofocus>

                                @if ($errors->has('code'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ $product->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('price_in') ? ' has-error' : '' }}">
                            <label for="price_in" class="col-md-4 control-label">Precio de entrada</label>

                            <div class="col-md-6">
                                <input id="price_in" type="text" class="form-control" name="price_in" value="{{ $product->price_in }}" required autofocus placeholder="$000.00">

                                @if ($errors->has('price_in'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('price_in') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('price_out') ? ' has-error' : '' }}">
                            <label for="price_out" class="col-md-4 control-label">Precio de salida</label>

                            <div class="col-md-6">
                                <input id="price_out" type="text" class="form-control" name="price_out" value="{{ $product->price_out }}" required autofocus placeholder="$000.00">

                                @if ($errors->has('price_out'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('price_out') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('unit') ? ' has-error' : '' }}">
                            <label for="unit" class="col-md-4 control-label">Unidades</label>

                            <div class="col-md-6">
                                <input id="unit" type="text" class="form-control" name="unit" value="{{ $product->unit }}" required>

                                @if ($errors->has('unit'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('unit') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('presentation') ? ' has-error' : '' }}">
                            <label for="presentation" class="col-md-4 control-label">Presentación</label>

                            <div class="col-md-6">
                                <input id="presentation" type="text" class="form-control" name="presentation" value="{{ $product->presentation }}" required>

                                @if ($errors->has('presentation'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('presentation') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-raised btn-primary">
                                    Editar producto
                                </button>
                                <a href="{{ route('products.index') }}" class="btn btn-raised btn-danger">
                                    ir al listado
                                </a>
                            </div>
                        </div>
                    </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/productList.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 text-right">
            <a href="{{ route( 'products.create' ) }}" class="btn btn-raised btn-primary">
                Crear Producto
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-primary">
                <div class="panel-heading">Productos registrados</div>

                <div class="panel-body">
                    <div class="row">
                        <table class="table table-striped table-hover ">
            				<thead>
            					<tr>
            						<th>ID</th>
                                    <th>Código</th>
            						<th>Nombre</th>
            						<th>Precio de entrada</th>
            						<th>Precio de salida</th>
            						<th>Unidades</th>
            						<th>Presentación</th>
            						<th>Acciones</th>
            					</tr>
            				</thead>
            				<tbody>
                    @foreach ($products as $product)
                            <tr>
                                <td>{{ $product->id }}</td>
                                <td>{{ $product->code }}</td>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->price_in }}</td>
                                <td>{{ $product->price_out }}</td>
                                <td>{{ $product->unit }}</td>
                                <td>{{ $product->presentation }}</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="javascript:void(0)" class="btn btn-primary btn-sm btn-raised">Acciones</a>
                                        <a href="#" class="btn btn-primary btn-sm btn-raised dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{{ route( 'products.show',$product->id )}}">Ver</a></li>
                                            <li><a href="{{ route( 'products.edit',$product->id )}}">Editar</a></li>
                                            <li class="divider"></li>
                                            <li><a href="{{ route( 'operations.list',['filter' => $product->id] )}}">Operaciones</a></li>
                                            <li class="divider"></li>
                                            <li><a href="javascript:void(0)" onclick="$('#deleteForm-{{$product->id}}').submit()">Eliminar</a></li>
                                            <form id="deleteForm-{{$product->id}}" action="{{ route( 'products.destroy',$product->id )}}" method="post">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                    @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection